spring:
  profiles:
    active: prod

springdoc:
  swagger-ui:
    path: "/"

server:
  port: 8080

app:
  message: Hola mundo desde Default
  envVariable: ${EXAMPLE_MESSAGE:default value}

#  error:
#    include-message: never
#    include-stacktrace: never
#spring:
#  application:
#    name: ob-rest
#  datasource:
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:C:/data/sample
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update